### ISSUE TITLE
libpng on Arch Linux

### ISSUE THREAD

**Issue by Obrekr** [SimulPiscator/AirSane#1]
Compiling on Arch Linux fails because of libpng not being found.

> /home/rosi/AirSane/imageformats/pngencoder.cpp:20:10: fatal error: libpng/png.h: No such file or directory
>  #include <libpng/png.h>
>           ^~~~~~~~~~~~~~
> compilation terminated.

Turns out libpng is available as 1.16 and 1.12 Version in two different packages and put in renamed subfolders to allow for parallel installation

> /usr/include/libpng16/
> /usr/include/libpng16/png.h

So creating a symlink fixed my build problem:
`ln -s /usr/include/libpng16/ /usr/include/libpng/`

**Comment by SimulPiscator** [comment]
Thanks for your note, I'll put it into the README file.
