### ISSUE TITLE
Make more clear that this is the server

### ISSUE THREAD

**Issue by Yetoo1** [SimulPiscator/AirSane#105]
In my researching how to share scanner connected by usb there are many repos and places with seemingly confusing/conflicting/counterintuitive terminology/descriptions/names. For a while I thought sane-airscan was the server I was looking for that could do this since its readme said that it's a backend and I thought AirSane was the client since the readme says it's a front end. I know now that sane-airscan is the client and AirSane is the server. I understand that the front end portion refers to AirSane's web interface and that eSCL is weird client/server wise when it comes to driverless scanning, but there should be more emphasis that this is the server for the relevant eSCL clients.

**Comment by SimulPiscator** [comment]
Thank you for pointing this out. I tried to clarify the wording a bit in the beginning of the README file.
I hope the relation between SANE, Apple AirScan, AirSANE, and sane-airscan have become a little bit clearer now.

**Comment by Yetoo1** [comment]
@SimulPiscator Thank you, I think the relation is much clearer now.
