### ISSUE TITLE
error at make install

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#11]
I also tried this after su root and it is the same.  Can you offer any advice?

Ubuntu 16.04_x86

sudo make install
Scanning dependencies of target airsaned
[  5%] Building CXX object CMakeFiles/airsaned.dir/server/main.cpp.o
In file included from /usr/include/c++/5/thread:35:0,
                 from /usr/src/AirSane/server/main.cpp:19:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/src/AirSane/server/scanner.h:26:0,
                 from /usr/src/AirSane/server/scanserver.h:22,
                 from /usr/src/AirSane/server/main.cpp:21:
/usr/src/AirSane/./sanecpp/sanecpp.h:45:14: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
 typedef std::shared_ptr<void> device_handle;
              ^
/usr/src/AirSane/./sanecpp/sanecpp.h:47:1: error: ‘device_handle’ does not name a type
 device_handle open(const std::string&, SANE_Status* = nullptr);
 ^
/usr/src/AirSane/./sanecpp/sanecpp.h:48:1: error: ‘device_handle’ does not name a type
 device_handle open(const device_info&, SANE_Status* = nullptr);
 ^
/usr/src/AirSane/./sanecpp/sanecpp.h:109:5: error: ‘device_handle’ does not name a type
     device_handle m_device;
     ^
/usr/src/AirSane/./sanecpp/sanecpp.h:115:29: error: field ‘device_handle’ has incomplete type ‘sanecpp::option_set’
     option_set(device_handle);
                             ^
/usr/src/AirSane/./sanecpp/sanecpp.h:106:7: note: definition of ‘class sanecpp::option_set’ is not complete until the closing brace
 class option_set
       ^
/usr/src/AirSane/./sanecpp/sanecpp.h:116:37: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     option_set(const option_set&) = delete;
                                     ^
/usr/src/AirSane/./sanecpp/sanecpp.h:117:48: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     option_set& operator=(const option_set&) = delete;
                                                ^
/usr/src/AirSane/./sanecpp/sanecpp.h:119:15: error: ‘device_handle’ is not a type
     void init(device_handle);
               ^
/usr/src/AirSane/./sanecpp/sanecpp.h:144:35: error: only declarations of constructors and conversion operators can be ‘explicit’
     explicit session(device_handle);
                                   ^
/usr/src/AirSane/./sanecpp/sanecpp.h:144:35: error: field ‘device_handle’ has incomplete type ‘sanecpp::session’
/usr/src/AirSane/./sanecpp/sanecpp.h:140:7: note: definition of ‘class sanecpp::session’ is not complete until the closing brace
 class session
       ^
/usr/src/AirSane/./sanecpp/sanecpp.h:157:5: error: ‘device_handle’ does not name a type
     device_handle m_device;
     ^
In file included from /usr/src/AirSane/server/scanserver.h:22:0,
                 from /usr/src/AirSane/server/main.cpp:21:
/usr/src/AirSane/server/scanner.h:35:31: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     Scanner(const Scanner&) = delete;
                               ^
/usr/src/AirSane/server/scanner.h:36:42: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     Scanner& operator=(const Scanner&) = delete;
                                          ^
/usr/src/AirSane/server/scanner.h:62:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
     std::shared_ptr<ScanJob> createJobFromScanSettingsXml(const std::string&, bool autoselectFormat = false);
          ^
/usr/src/AirSane/server/scanner.h:63:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
     std::shared_ptr<ScanJob> getJob(const std::string& uuid);
          ^
/usr/src/AirSane/server/scanner.h:66:25: error: ‘shared_ptr’ is not a member of ‘std’
     typedef std::vector<std::shared_ptr<ScanJob>> JobList;
                         ^
/usr/src/AirSane/server/scanner.h:66:25: error: ‘shared_ptr’ is not a member of ‘std’
/usr/src/AirSane/server/scanner.h:66:51: error: ‘JobList’ was not declared in this scope
     typedef std::vector<std::shared_ptr<ScanJob>> JobList;
                                                   ^
/usr/src/AirSane/server/scanner.h:66:51: error: template argument 1 is invalid
/usr/src/AirSane/server/scanner.h:66:51: error: template argument 2 is invalid
/usr/src/AirSane/server/scanner.h:66:18: warning: ‘typedef’ was ignored in this declaration
     typedef std::vector<std::shared_ptr<ScanJob>> JobList;
                  ^
/usr/src/AirSane/server/scanner.h:67:5: error: ‘JobList’ does not name a type
     JobList jobs() const;
     ^
/usr/src/AirSane/server/scanner.h:69:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
     std::shared_ptr<sanecpp::session> open();
          ^

**Comment by SimulPiscator** [comment]
Thanks, I think I fixed the problem in the CMakeLists.txt file.
