### ISSUE TITLE
Scanimage -L shows scanners but none in web interface nor mopria

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#111]
I had just installed this in an old Raspbian 9 install and it was working, except for document feeder. Now I took that Pi3B+ and upgraded to Debian 11 and I get completely different behavior.

First I can see scanners on the Pi itself via SANE-AirScan protocol and another via hpaio. Scanners seem to work on Pi server with Document Scanner app.

I removed all protocols from the ignore.conf

On the web interface I still see no scanners.

in Mopria I see no shared scanners

While on the subject of ignore list I, I also ask for clarification of ignore.conf and ignorelist.conf are these supposed to be two separate files or is there some confusion as to the file's actual name? I see references to the file ignorelist.conf in docs , but there is only an ignore.conf installed

Avahi is running but it says no service file . Should it have one?

`$ systemctl status avahi-daemon.service
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
     Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-10-03 07:21:31 PDT; 18min ago
TriggeredBy: ● avahi-daemon.socket
   Main PID: 363 (avahi-daemon)
     Status: "avahi-daemon 0.8 starting up."
      Tasks: 2 (limit: 779)
        CPU: 1.057s
     CGroup: /system.slice/avahi-daemon.service
             ├─363 avahi-daemon: running [raspberrypi.local]
             └─373 avahi-daemon: chroot helper

Oct 03 07:21:36 raspberrypi avahi-daemon[363]: Registering new address record for 2601:1c2:1702:88a0:fab8:bbd8:2dbb:2f39 on wlan0.*.
Oct 03 07:21:36 raspberrypi avahi-daemon[363]: Withdrawing address record for fe80::ab6f:ad90:3d5a:720f on wlan0.
Oct 03 07:21:37 raspberrypi avahi-daemon[363]: Registering new address record for 2601:1c2:1702:88a0::fd9b on wlan0.*.
Oct 03 07:21:39 raspberrypi avahi-daemon[363]: Joining mDNS multicast group on interface wlan0.IPv4 with address 10.0.0.250.
Oct 03 07:21:39 raspberrypi avahi-daemon[363]: New relevant interface wlan0.IPv4 for mDNS.
Oct 03 07:21:39 raspberrypi avahi-daemon[363]: Registering new address record for 10.0.0.250 on wlan0.IPv4.
Oct 03 07:21:40 raspberrypi avahi-daemon[363]: Got SIGHUP, reloading.
Oct 03 07:21:40 raspberrypi avahi-daemon[363]: No service file found in /etc/avahi/services.
Oct 03 07:21:41 raspberrypi avahi-daemon[363]: Got SIGHUP, reloading.
Oct 03 07:21:41 raspberrypi avahi-daemon[363]: No service file found in /etc/avahi/services.`

**Comment by SimulPiscator** [comment]
> First I can see scanners on the Pi itself via SANE-AirScan protocol and another via hpaio. Scanners seem to work on Pi server with Document Scanner app.
>I removed all protocols from the ignore.conf
>On the web interface I still see no scanners.
>in Mopria I see no shared scanners

`airsaned` runs as user `saned`. Maybe there is an issue with `saned` not being in the "scanner" group?

> While on the subject of ignore list I, I also ask for clarification of ignore.conf and ignorelist.conf are these supposed to be two separate files or is there some confusion as to the file's actual name? I see references to the file ignorelist.conf in docs , but there is only an ignore.conf installed

Thanks for the note. There was a typo in the README file, which is now fixed.

> Avahi is running but it says no service file . Should it have one?

An Avahi service file is only for static configuration of services AFAIK. I don't think Avahi needs it.

**Comment by markosjal** [comment]
saned does have access to scanners:
`sudo -u saned scanimage -L
device `airscan:w1:Brother MFC-7360N' is a WSD Brother MFC-7360N ip=10.0.0.84
device `hpaio:/net/hp_officejet_pro_9010_series?ip=10.0.0.55&queue=false' is a Hewlett-Packard hp_officejet_pro_9010_series all-in-one
`

**Comment by SimulPiscator** [comment]
Maybe you should set LOCAL_SCANNERS_ONLY to "false" in /etc/defaults/airsaned ?

**Comment by markosjal** [comment]
yes that does it. 

I guess I missed that file on the new install . 

The file/path is actually /etc/default/airsane in case anyone is looking for the same file and not finding it with path/file in previous post
