### ISSUE TITLE
continuous scans show up vertically compressed

### ISSUE THREAD

**Issue by mo-pyy** [SimulPiscator/AirSane#113]
When scanning multiple pages using gnome document scanner, the pages go vertically compressed. See this example pdf:
[malformed_airsane_scan.pdf](https://github.com/SimulPiscator/AirSane/files/12886828/malformed_airsane_scan.pdf)

When scanning using `scanimage` from the server running AirSane, this does not happen and when running it from a remote device using airscan sane backend, it does happen, so if I understand it correctly it should be related to AirSane.

AirSane is compiled from the latest master, commit `918fd7bf76dada4e534b91558a51f486cf209879`.

**Comment by SimulPiscator** [comment]
If you use AirSane's web interface and choose "PDF" as format, and "Feeder" as source, does the same problem occur?

**Comment by SimulPiscator** [comment]
You might try the latest version from git. It has been changed to improve behavior with Automatic Document Feeders.

**Comment by mo-pyy** [comment]
Thanks for your answer. I just updated to the latest version from git.
Actually I don't have an ADF, I was simply scanning multiple times. In the web interface, I have selected 'Platen', it's the only available input source. I could not reproduce the error in the web interface. But I could reproduce it again using the gnome scanner. 
I noticed, that just a part of the document gets compressed, see here 
[malformed_airsaned_scan_v2.pdf](https://github.com/SimulPiscator/AirSane/files/12910479/malformed_airsaned_scan_v2.pdf)
I probably put the paper in the other way around. Do you think it could be a sane driver fault?
Journalctl show this error multiple times while scanning:
```
io/hpmud/dot4.c 120: unexpected DOT4CreditRequest: cmd=4, hid=4, pid=4, maxcredit=65535
```

**Comment by mo-pyy** [comment]
I just scanned again on the server using `scanimage` and now the first page also was affected, but the following 5 weren't.  Maybe this isn't AirSane related

**Comment by SimulPiscator** [comment]
> Maybe this isn't AirSane related
No irregularities show up when testing AirSane with SANE's "test" backend, or my physical scanner,  a Canon LiDE 60.

**Comment by mo-pyy** [comment]
Okay thanks, then I am closing this for now.
