### ISSUE TITLE
ADF source fails with HP ScanJet Pro 2000 s2

### ISSUE THREAD

**Issue by gabrieleturchi** [SimulPiscator/AirSane#118]
When scanning with --source "ADF Duplex" everything works fine, but without --source options, or with plain ADF argument, the image appear to be a narrow and very long  gray bar.

**Comment by gabrieleturchi** [comment]
Sorry, published a bug on the wrong repo... My apologies!

**Comment by SimulPiscator** [comment]
No problem.
