### ISSUE TITLE
No such file or directory issue

### ISSUE THREAD

**Issue by SerJoG** [SimulPiscator/AirSane#121]
Hello, @SimulPiscator
I'm using the latest release of airsane and sane on a Raspberry pi 3 model B+.
When I run the make command the following error appear:
![image](https://github.com/SimulPiscator/AirSane/assets/23215134/55ed3ceb-f7bb-4903-907a-0fbfac411212)

**Comment by SimulPiscator** [comment]
Hi,

you need to install the sane-dev packet so you have the SANE header available in your system.

**Comment by SerJoG** [comment]
I jumped a command. Now I try again and inform you.

**Comment by SerJoG** [comment]
The make is working but I want to tell you that this show up:
![image](https://github.com/SimulPiscator/AirSane/assets/23215134/15141fad-a29d-49ea-bbe8-48740adebdda)
And also other.

**Comment by SimulPiscator** [comment]
It's a warning about a change within gcc that will affect sharing compiled C++ code with others.
Regarding the AirSane executable, it may be ignored.
(See https://stackoverflow.com/questions/48149323/what-does-the-gcc-warning-project-parameter-passing-for-x-changed-in-gcc-7-1-m)

**Comment by SerJoG** [comment]
Now I can acces to the web page but `sudo -u saned scanimage -L` doesn't show airscan device but only xerox.

**Comment by SerJoG** [comment]
I also have installed cups, it may 'cause problem?

**Comment by SimulPiscator** [comment]
So I guess you want to publish your Xerox scanner to Windows?

**Comment by SimulPiscator** [comment]
Which user account are you running AirSane under?

**Comment by SerJoG** [comment]
How could I find which?

**Comment by SimulPiscator** [comment]
When you are logged in to the machine, what exact command are you executing to run AirSane?

**Comment by SerJoG** [comment]
I just started the service on systemctl, I didn't use other command. I know that's airsaned but I thought its for change settings only.

**Comment by SimulPiscator** [comment]
OK, if it runs from systemctl, it will will run as saned. So if you run `scanimage -L `as saned, it sees the Xerox scanner, but if you run AirSane as saned, it doesn't see it?

**Comment by SimulPiscator** [comment]
If you stop airsaned through systemctl, you can do the following:
`sudo -u saned /usr/sbin/airsaned --debug=true --local_scanners_only=false`

**Comment by SerJoG** [comment]
@SimulPiscator Hi, there no airsaned in /usr/sbin. But I today I found that stopping and starting again airsaned solved the issue.
