### ISSUE TITLE
SOLVED! Clean Linux Mint 19.1 install error running

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#14]
I just did a clean install of Mint 19.1 after seeing that ubuntu 16.04 has issues with PNG support.

I can get all the way through building and installing then I get the following at sudo systemctl ststus airsand   (full status pasted below)

io/hpmud/pp.c 627: unable to read device-id ret=-1

I am currently using the SANE test back-end tester but as far as  I can see it works in Simple Scan . I then reduced the number of virtual scanners to 1 (default is 2) 

Also I tried to access http://localhost:8090/eSCL/ScannerStatus and get a page not found but as I understand it an AirScan Scanner (AirSANE in this case) should respond to that URL.

sudo systemctl status airsaned
● airsaned.service - AirSane Imaging Service
   Loaded: loaded (/lib/systemd/system/airsaned.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-06-06 14:19:47 CDT; 8min ago
 Main PID: 2722 (airsaned)
    Tasks: 6 (limit: 4464)
   CGroup: /system.slice/airsaned.service
           └─2722 /usr/local/bin/airsaned --interface=* --listen-port=8090 --access-log= --hotplug=true --mdns-announce=true -

Jun 06 14:19:47 mark-HP-EliteBook-6930p systemd[1]: Started AirSane Imaging Service.
Jun 06 14:19:47 mark-HP-EliteBook-6930p airsaned[2722]: io/hpmud/pp.c 627: unable to read device-id ret=-1
lines 1-10/10 (END)

**Comment by markosjal** [comment]
Partially solved
I went to  /etc/sane.d/dll.d edited the two files I found there commenting out the only active lines . One was hplip which I suspect was the culprit. Still unable to see the xml I should see when I go to http://localhost:8090/eSCL/ScannerStatus

**Comment by SimulPiscator** [comment]
The scanner status page is not where you expect it to be. AirSane assigns an UUID to each scanner and makes it part of the scanner's URL, otherwise it could not support multiple scanners. To see a scanner's UUID, open AirSane's root URL in a browser, or use avahi-discover to read the zeroconf (avahi) announcements that AirSane provides. The scanner status URL is then /<uuid>/ScannerStatus, and so on.

**Comment by markosjal** [comment]
You are good at closing unresolved tickets.

I am telling you there is no XML anywhere, I checked.

I am aware that the URL is probably http://localhost/UUID/ScannerStatus . I suspect this is why the Avahi text entry  rs=UUID . I did try that too, even though your answer seemed  somewhat unspecific I think that is what you meant.

Now I even tested with OSX mojave. Image capture shows the scanner then spends some time trying to connect then "An Error Occurred while communicating with the scanner (-9923) " 

I am pretty sure that OSX is seeing the same thing I see no xml anywhere. I can put it on wireshark to be sure but that seems to be a lot of debugging when I already know the xml is unavailable.

**Comment by markosjal** [comment]
a restart now DOES allow me to see the XML I have no idea why. Stuill getting erros from OSX though
"An Error Occurred while communicating with the scanner (-9923) "
both in preview and Image Capture , same error

**Comment by markosjal** [comment]
Might be noteworthy Your Avahi advertisement fpr rs= has a slash before the UUID . Other devices I do not see this 

Yours 
rs=/UUID

Others
rs=eSCL


Also worth noting that the following are not working with AirSANE
OSX 10.14 Mojave
Mopria Scan for Android
VueScan (has built in eSCL capabilities)

**Comment by SimulPiscator** [comment]
Could it be you have a firewall running that blocks access to port 8090 from outside? You can test this by trying "telnet localhost 8090" from the machine running AirSane, and then by trying to telnet to port 8090 from another machine.

**Comment by markosjal** [comment]
Here is te problem 

airsaned --help says
 --local-scanners-only=true	ignore SANE network scanners


when in reality setting this to false means that none of the XML is available on the network, only to Localhost

**Comment by markosjal** [comment]
I had marked this as Solved thinking I found the answer, however after a reboot I am now back to having the eSCL/Airscan only on Localhost . It is a mystery to me.Making the change mentioned earlier seemed to do the trick for one reboot but now as it was before.
