### ISSUE TITLE
VueScan does not detect Scanner

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#16]
VueScan, I believe should detect the scanner from the Avahi advertisement as it does with tested eSCL Scanners and this project https://github.com/markosjal/AirScanning.

Vuescan simply is looking for something it is not seeing or understanding in the Avahi/Bonjour advertisement . This was tested on Localhost and over LAN with current VueScan Version

**Comment by SimulPiscator** [comment]
VueScan assumes that any eSCL scanner is located on a network resource beginning with /eSCL. Also, it seems to consider only scanners which are announced with rs=eSCL. It is thus VueScan's, and not AirSane's problem that VueScan does not recognize AirSane scanners.

You can see this by running the strings command on the VueScan executable, and filtering for eSCL:
```
% strings VueScan|grep eSCL
rs=eSCL
GET /eSCL/ScannerCapabilities HTTP/1.1
GET /eSCL/%s/NextDocument HTTP/1.1
POST /eSCL/ScanJobs
GET /eSCL/ScannerStatus HTTP/1.1
DELETE /eSCL/%s HTTP/1.1
POST /eSCL/ScanJobs HTTP/1.1
/eSCL/
eSCL    
```

**Comment by SimulPiscator** [comment]
AirSane does now publish the first scanner in its list of scanners as /eSCL if its `compatible-path` option is set. This has been confirmed to work with VueScan. Note that it not possible to serve more than one scanner to VueScan this way.
