### ISSUE TITLE
Just so you are aware and perhaps can conform

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#17]
from https://ftp.pwg.org/pub/pwg/candidates/cs-ippscan10-20140918-5100.17.pdf

rs Resource portion of Scanner URI without leading
slash.

It is in table 10 page 42 of mentioned document

**Comment by SimulPiscator** [comment]
Right, except that the document is defining the IPP rather than the eSCL protocol. A web search for eSCL txt records turned up both rs=/eSCL and rs=eSCL. It seems good practice to omit leading slashes in mdns txt records, though, so I followed your suggestion and removed the slash.
