### ISSUE TITLE
I think you are on to something great here. 

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#18]
I think you are on to something great here.  

I recently wrote an email to the SANE Devs list that to date, has not received an reply. I think the antiquated SANE over network needs to be seriously revamped for something more modern and a standard in use today, CUPS has managed to keep up with the times and did so before Apple aquired it. SANE needs to follow that example. 

There are three potential models 
eSCL/AirScan 
WSD 
IPP scanning 

Any of which if replacing SANE over network would be better than what we have now. I think the first two are xml based, not sure about the third. It is far too easy to read ScannerSettings and derive settings to submit an xml to POST then read the resulting file. It opens up new ways for machine to machine communication, which as we step in to the 21st centrury becomes more and more important. Maybe today you do not need your refridgerator to scan something but tomorrow some new whizbang device will come out incorporating one of these standards. This is without mentioning the ease with which one might convert WSD xml to eSCL xml or visa versa;

What you have here is the potential foundation for that, with the single exception that SANE still has no eSCL Back-end. If such a back-end existed the need for the antiquated SANE over network protocol would be eliminated.

**Comment by SimulPiscator** [comment]
I don't think the SANE network protocol is antiquated. It fits its purpose to provide access to any scanner property exported by backends, which is not possible through the communication protocols you mention.

It might be possible to transform the SANE network protocol into something XML-based and maybe even eSCL compatible but I wouldn't see the point. IMHO, the SANE network protocol is fine as it is.
