### ISSUE TITLE
No real issue, just to express my gratitude, this piece of software is really something, everyone messing with SANE should give it a try!

### ISSUE THREAD

**Issue by linxucc** [SimulPiscator/AirSane#20]
This AirSane is really something, it should be added to the SANE's project page, and recommend everyone give it a try.

Other remote frontend of SANE is either outdated(TwainSane) or have problems here or there (phpsane, scanserv and it's updated version scanservjs, some java frontends.....). 
Before I found this, I have already give up searching, and prepared my self to write something similar myself, to get this simple scan functionality just work through my Lan...

Everything in AirSane works just like expected, and beyond! 
The Apple's AirScan protocol works fairly well without any further mess, open the image capture app in my iMac and the scanner is just there, everything just works.

Even the installation guide's quality is the best, with great clarity, I don't get a single error during the process, just copy and paste your command and it's just built and work fine. I really hope all the other software programmer's can do just the same, then we can save a lot time and cheer.

Anyway, thank you man, you got me saved. Keep moving on, make AirSane the best SANE frontend up to date!

**Comment by SimulPiscator** [comment]
Thank you for your very kind words.
