### ISSUE TITLE
Invalid read of size 8 - SIGSEGV with Brother DCP-L2510 (brscan4-0.4.8-1.amd64.deb)

### ISSUE THREAD

**Issue by pawpro** [SimulPiscator/AirSane#22]
Many thanks for this project.

I have just given Airsaned a try on Ubuntu 18.04.2.
`scanimage -d "brother4:bus5;dev1" --format tiff > raw.tiff `
works great every time.

On OSX Mojave the Image Capture keeps refreshing the list of shared scanners upon clicking on the the scanner. But Airsaned does not exit. 
While trying to access the scanner via the web interface it crashes with "Segmentation fault (core dumped)"
I built it with debug symbols and attached the valgrind output.
This is how I run it

`airsaned --local-scanners-only=true --debug=true`

```
enumerating local devices...
sane_init(nullptr, nullptr)
sane_exit()
found: brother4:bus5;dev1 (Brother DCP-L2510D)
sane_init(nullptr, nullptr)
sane_open(brother4:bus5;dev1) -> 0xaa96d80
sane_close(0xaa96d80)
sane_exit()
uuid: 3406f97c-f7d4-58d1-92f4-551373ed15bf
published as 'Brother DCP-L2510D'
listening on 127.0.0.1:8090
listening on 10.0.1.194:8090
listening on ::1:8090
listening on fe80::5054:ff:fe66:13cb:8090
Segmentation fault
```
[out.txt](https://github.com/SimulPiscator/AirSane/files/3571485/out.txt)

**Comment by SimulPiscator** [comment]
Thanks for your great bug report. I could identify the issue to be due to nonstandard values in the scan mode option, and committed a fix for it.

Please let me know if your problem is solved with the current version of AirSane.
