### ISSUE TITLE
AirSane inconsistently segfaults on init with the default list of backends enabled in dll.conf

### ISSUE THREAD

**Issue by patters-syno** [SimulPiscator/AirSane#24]
This one confused me. In my testing I had commented out all the backends except my own scanner's plustek one and _airsaned_ was very reliable - starting and stopping as expected hundreds of times as I developed the package for Synology NAS.

However, now that I am close to release-ready, when testing a fresh installation of the very same sane-backends 1.0.28 (with libusb 1.0.23 since the system has a pre-v1.0 version) _airsaned_ would not start:
```
enumerating local devices...
sane_init(nullptr, nullptr)
Segmentation fault (core dumped)
```

Oddly, it would start if sane was removed from the inetd config. This is the same system I have used since the start, and the only difference I can find is that now the list of enabled backends is back to the very inclusive default state.

AirSane returns to a reliable working state once all the unwanted backends are commented out from _etc/sane.d/dll.conf_.

Trying again several times I find that sometimes it works fine despite all the backends remaining enabled. In summary then it appears to be inconsistent with all backends enabled, and reliable when most of them are commented out. I notice that your README recommends to comment out unused ones, so is there a timeout issue in _airsaned_ perhaps during device detection? Ideally I want this to be a package that requires no manual configuration, so most users will in fact have the default inclusive list.

_sane-find-scanner -q_ and _scanimage -L_ worked fine throughout - and presumably AirSane's device enumeration will be using those same sane library functions so I think it's unlikely the cause of the issue lies with sane-backends.

Any ideas?

**Comment by SimulPiscator** [comment]
The segfault happens during or immediately after searching for devices. I improved logging so we can see whether it's during or after. Could you give it a try with the current version in my repo? Thank you so much.

**Comment by patters-syno** [comment]
```
root@DS214play:/volume1/public# /var/packages/AirSane/target/bin/airsaned --debug=true
enumerating local devices...
sane_init(nullptr, nullptr)
sane_get_devices() ...
... sane_get_devices() -> SANE_Status Success
sane_exit()
found: plustek:libusb:001:005 (Canon CanoScan N670U/N676U/LiDE20)
sane_init(nullptr, nullptr)
sane_open(plustek:libusb:001:005) -> 0xb5e008a8
sane_close(0xb5e008a8)
sane_exit()
uuid: 705c14c7-033d-5ec3-a814-2f44454d30aa
published as 'Canon CanoScan N670U/N676U/LiDE20'
listening on 127.0.0.1:8090
listening on 192.168.1.203:8090
listening on ::1:8090
listening on 2a02:c7f:c222:e500:211:32ff:fe2d:750f:8090
listening on fdc5:d007:b672:0:211:32ff:fe2d:750f:8090
listening on fe80::211:32ff:fe2d:750f:8090
^C
root@DS214play:/volume1/public# /var/packages/AirSane/target/bin/airsaned --debug=true
enumerating local devices...
sane_init(nullptr, nullptr)
sane_get_devices() ...
Segmentation fault (core dumped)
root@DS214play:/volume1/public#
```

**Comment by SimulPiscator** [comment]
Right, it's out of my hands. Chances are that one of the sane backends has a bug that is triggered by something on the airsaned side. By disabling either half of the backends, one could try which half displays the bug, then again disable either half of that part, etc. If it is not too cumbersome for you, a small number of halving steps can narrow down which backend is to blame.

**Comment by patters-syno** [comment]
There really doesn't seem much of a pattern to it unfortunately. I did just randomly get this though:
enumerating local devices...
```
sane_init(nullptr, nullptr)
sane_get_devices() ...
process 14875: arguments to dbus_message_unref() were incorrect, assertion "message->generation == _dbus_current_generation" failed in file dbus-message.c line 1618.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```
I'll try compiling SANE without avahi (which will remove the dbus dependency I think).

**Comment by patters-syno** [comment]
Yes that does seems to have fixed the stability issues. So a workaround more than a fix, but you can't use avahi when saned is invoked by inetd in any case, so no great loss in my use case.

**Comment by SimulPiscator** [comment]
Great work, thank you!
Seems there is nothing we can do about it, except for disabling saned, right?

**Comment by patters-syno** [comment]
saned can run (and the issue goes away) when it's compiled without avahi support. It's no loss in my use case since most front ends need to statically attach to the specific USB bus ID of the backend and when that changes the front end usually has to be reconfigured anyway. That's why AirSane is so great - it removes all that complexity.

**Comment by SimulPiscator** [comment]
I'll close the issue then. Thanks again for all your help.
