### ISSUE TITLE
AirSane is not showing scanner that scanimage -L shows

### ISSUE THREAD

**Issue by GuiAlDuS** [SimulPiscator/AirSane#25]
Hi!
This is a recent problem that didn't appear weeks (or months) ago when I installed AirSane for the first time.
The problem appeared on a RaspberryPi 3 B+ with Raspbian Buster.

I followed all instructions for installing AirSane, I have done it before with same scanner and same Raspberry Pi but on Raspbian Stretch and worked perfectly. Now it installed nicely but AirSane is not showing the scanner.

If I run `sudo scanimage -L ` I get the right scanner: `device epson2:libusb:001:004 is a Epson GT-9800 flatbed scanner`

But on the AirSane server I get that there are no scanners:

> Scanners
> 
> No scanners available
> 
> Build
> 
> date: Oct 12 2019, 18:22:53
> 
> commit: 7fbaa42 (branch master, revision 44)

Any idea what can be causing this problem?

And by the way, thanks for such a wonderful tool...

**Comment by SimulPiscator** [comment]
Hi,

there might be a problem with device permissions. When you run scanimage as user saned, will it list the scanner?
`sudo su - saned scanimage -L`

**Comment by GuiAlDuS** [comment]
Thanks for your response

If I run `sudo su - saned scanimage -L` I get `su: invalid option -- 'L'`

But if I run `sudo su - saned scanimage-L` then I get:

```
su: warning: cannot change directory to /var/lib/saned: No such file or directory
This account is currently not available.
```

**Comment by SimulPiscator** [comment]
Sorry, the command does not work for users without a shell, and there were quotes missing, too.
The correct command is `sudo -u saned scanimage -L`.

**Comment by GuiAlDuS** [comment]
When I run `sudo -u saned scanimage -L` I get that `No scanners were identified.`
How can I change the device permissions to the saned user?

Thanks for your help!
