### ISSUE TITLE
A request more than an issue

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#28]
I am looking for wireshark (or other) traces of successful eSCL/AirScan scans. If anyone can help please .

I am looking for all exchanges between scanner and client from scanner detection all the way through to client loading the image.

I have no eSCL devices here. I would prefer to see it from a Mac to an "officially supported" scanner but will take what I can get.

You can send them to markosjal at the email with a G.

**Comment by SimulPiscator** [comment]
If you can omit the "officially supported" part, you may record the data exchange between a Mac and a Linux machine running AirSane.

**Comment by SimulPiscator** [comment]
I see that you compiled an eSCL page at https://gist.github.com/markosjal.
Given it's finished, I think that I can close this issue now.
