### ISSUE TITLE
OpenWRT build?

### ISSUE THREAD

**Issue by tbaela** [SimulPiscator/AirSane#29]
Hello! Is it possible to build AirSane for OpenWRT?
I'm currently using sane, but I had to use command line to scan.
It would be great if I could use my scanner via default "Image Capture" OS X app

**Comment by SimulPiscator** [comment]
I haven't tried but I don't see a reason why not, once you have the dependencies in place. libjpeg and libpng, libavahi-client and libusb1 should be available in OpenWRT.

**Comment by tbaela** [comment]
Yes, they are available. I'm not really experienced with Makefiles, so I need some help to make it possible to build for OpenWRT.

**Comment by SimulPiscator** [comment]
A simple makefile should do. You need compiler flags to enable C++11 support, otherwise it's just straight compiling all of the .cpp files and linking them together. I'm not particularly good at makefiles either, otherwise I would write one for you.

**Comment by tbaela** [comment]
Wow, I did it!
If I manage to make it fully working, I'll post details.

**Comment by SimulPiscator** [comment]
Cool!

**Comment by tbaela** [comment]
Here's my result: https://github.com/tbaela/AirSane-openwrt

**Comment by SimulPiscator** [comment]
Looks great, thank you!

**Comment by SimulPiscator** [comment]
I noticed that you changed the default port from 8090 to 8089 in the OpenWRT build. If you are aware of any collisions on port 8090, I would consider changing to port 8089 in the AirSane sourcecode as well.

**Comment by tbaela** [comment]
> I noticed that you changed the default port from 8090 to 8089 in the OpenWRT build. If you are aware of any collisions on port 8090, I would consider changing to port 8089 in the AirSane sourcecode as well.

Just forgot to change it back after testing config file :)

**Comment by SimulPiscator** [comment]
Ah, ok. Thanks.
