### ISSUE TITLE
AirScan documentation

### ISSUE THREAD

**Issue by mblythe86** [SimulPiscator/AirSane#3]
I'm interested in basically writing the reverse of this code - a SANE **backend** that talks to AirScan/eSCL devices on the network, and allows existing SANE frontends (e.g. xsane) to scan from them.

You say this in your README:

> AirSane has been developed by reverse-engineering the communication protocol implemented in Apple's AirScanScanner client

Would you be willing to share your reverse-engineering notes?  Or any resources you may have found that documents this protocol?

**Comment by SimulPiscator** [comment]
I've been using Hopper disassembler (https://www.hopperapp.com/) on Apple's AirScanScanner exexecutable. AirScanScanner is written in ObjectiveC, which Hopper is able to transform into something close to source code, so it's straightforward to understand.
Further, a google search for "escl airscan" will turn up David Poole's blog, and a python-scan-eSCL project on Github.
