### ISSUE TITLE
Synology application stop working

### ISSUE THREAD

**Issue by IDSokolov** [SimulPiscator/AirSane#31]
When open Capture Application on MacOS Catalina 10.15, selecting "sharing" scanner (this scanner connecting to Synology NAS and shares by AirSane application running on NAS) and trying to receive preview picture, scanner start to scan but at the end of scanning it shows that connection to shared scanner is lost and it does not appear in "shared" list. In NAS AirSane application appears as stopped and needs to be restarted. This continues every time when trying to scan from Capture Application.

**Comment by SimulPiscator** [comment]
Can you open http://ip-of-your-nas:8090 in a web browser, click the name of your scanner, and try scanning from the web interface?

**Comment by IDSokolov** [comment]
When i try to make scan from Browser same situation. Scanner desappers when scanner job seems to be final and AirSane application stop working.

**Comment by SimulPiscator** [comment]
Can you scan using `scanimage` from the command line when logging in to your NAS?
