### ISSUE TITLE
Failed to Connect from Image Capture

### ISSUE THREAD

**Issue by hftsai256** [SimulPiscator/AirSane#32]
I have set up AirSane server on Debian Buster/Arm64 and can download scanned images on http://<hostname>:8090. On MacOS Catalina side, the scanner pops up in Image Capture and also shown up as Bonjour Scanner. However it throws the error "Failed to open a connection to the device (-21345)".

I then tried to get some log on the server end as instructed:
sudo -u saned airsaned --debug=true --access-log=-
It shows nothing when I am connecting with Image Capture. However it can tell me when I access the web interface. I'm wondering if my avahi is not set up properly?

**Comment by SimulPiscator** [comment]
I remember having such problems when ipv6 was disabled on the device running AirSane. You should make sure that ipv6 is enabled on your local network as well.

To check which information is being sent through avahi, you can download the "Discovery" utility from the Mac App Store (http://www.tildesoft.com/). It will let you browse all services announced on your local network.

**Comment by hftsai256** [comment]
I renewed DHCP with ipv6 addresses enabled. Image Capture can now connect without issue. Thanks for your help and all the hard work to make this happened :)

**Comment by himanshubabal** [comment]
> I renewed DHCP with ipv6 addresses enabled. Image Capture can now connect without issue. Thanks for your help and all the hard work to make this happened :)

I am facing the same issue.
Can you please clarify what 'renewing DHCP Lease' means & how to do it.

**Comment by SimulPiscator** [comment]
```
sudo ifdown eth0
sudo ifup eth0
```
should renew the DHCP lease on the machine running AirSane.
Alternatively, rebooting the machine will renew the DHCP lease as well.

**Comment by himanshubabal** [comment]
Rebooting the machine worked.
Thanks for the prompt reply
