### ISSUE TITLE
Add Hostname in Published Name?

### ISSUE THREAD

**Issue by hftsai256** [SimulPiscator/AirSane#34]
I would like to add `@ $hostname` after the shared Bonjour name (same behavior as CUPS/mDNS). For example:
![Screen Shot 2020-07-29 at 5 03 59 PM](https://user-images.githubusercontent.com/30164527/88853298-821a3080-d1bd-11ea-8b0a-0b71d0e6d460.png)
I looked around file `zeroconf/mdnspublisher.cpp` but not sure where to inject the additional string. This is not super important but a good-to-have feature. This additional hostname can also merge with CUPS when played right for multifunction printers.
Thanks again.

**Comment by SimulPiscator** [comment]
You may change the service name here if you like: https://github.com/SimulPiscator/AirSane/blob/07c5b6bd9c46999c9b9d614d42c62d2cd03abbff/server/scanserver.cpp#L210
The hostname is available as this->hostname().
