### ISSUE TITLE
Scanner not discovered on my Mac

### ISSUE THREAD

**Issue by itsab1989** [SimulPiscator/AirSane#35]
I recently installed the precompiled Sane backends and AirSane from pcloadletter on my synology DS414. I can now access my scanner (a Canon Lide 700F) via my browser and scan images that way.
However I cannot add it in my Macs (latest version of Mojave) Printer and Scanner settings or access it in the Image Capture app.
Today I opened a Finder window and navigated to the Airscan app you mentioned in your description (system - library - image capture...) and double clicked on it. Suddenly the scanner appeared and I was able to add it.
However after a reboot I couldn’t manage to get it working again. Do I miss anything?

**Comment by SimulPiscator** [comment]
Maybe there is an issue with your network configuration? The order in which networks appear in your "Networks" control panel has an impact on mDNS resolution. Also, it may depend on whether there is an active network cable plugged into your MacBook or not. You can select whether WiFi or Ethernet should have priority in case both are connected.

**Comment by itsab1989** [comment]
I just checked and everything seems to be in correct order. I tried another device (wifi printer / scanner) on another network a few hours ago and that worked instantly. It's not a big issue as long as I can scan via browser. It would be just more convenient to have the scanner directly available in all of my applications.

**Comment by SimulPiscator** [comment]
If you want to analyze issues with your network, the "Discovery" app may be helpful. It allows you to display all Bonjour (mDNS) services announced currently in your network:
http://www.tildesoft.com/
The service type of a Bonjour scanner is _uscan._tcp.

**Comment by itsab1989** [comment]
I installed the Discovery app on my iPhone. A few seconds after I started it it showed an entry with the name "_uscan._tcp."
However if I tap that an empty list appears with a spinning circle and it just says "Scanning..."![image](https://user-images.githubusercontent.com/66096713/89040224-b3246d80-d343-11ea-9936-aaaf1cb4b36d.jpeg)![image](https://user-images.githubusercontent.com/66096713/89040231-b7508b00-d343-11ea-9794-15db2aab5896.png)

**Comment by SimulPiscator** [comment]
It might be that you have a misconfiguration in the local network. Especially check whether the netmask setting agrees on all machines attached to the network (ifconfig or /sbin/ifconfig on the command line).

**Comment by itsab1989** [comment]
I checked that and it is the same on all of my devices.

**Comment by itsab1989** [comment]
I cannot tell you why, but it seems to be working now. Even after a reboot.
I once again tried to reset the server in the airsane options and navigated to the airscan app in the finder. Once I double clicked on it the scanner popped up and I could add it. Fingers crossed it stays that way.

Thanks for your great work!
