### ISSUE TITLE
Oki-MC853: Error during device I/O

### ISSUE THREAD

**Issue by roro60** [SimulPiscator/AirSane#37]
When trying to scan with an Oki_MC853 on Debian testing, I always get the error "Error during device I/O" with sane. The eScl/ScanJobs always returns 400 Bad request. But if I try the same with curl, the scan succeeds.

 
[xscanimage-OKI-MC853-FEA6D2.log](https://github.com/SimulPiscator/AirSane/files/5445274/xscanimage-OKI-MC853-FEA6D2.log)

**Comment by SimulPiscator** [comment]
It seems this is a problem with sane-airscan or sane-escl, not with AirSane. AirSane is used to publish SANE devices via AirScan. In contrast, you have an AirScan/eSCL scanner that you try to use via SANE.
sane-airscan (https://github.com/alexpevzner/sane-airscan) and sane-escl (https://gitlab.com/sane-escl/sane-escl) are two sane backends that allow accessing AirScan/eSCL scanners. You should report your problem there, depending on which of the two you are actually using.

**Comment by roro60** [comment]
You are right, I mixed up the projects. Thank you!
