### ISSUE TITLE
segfault on unavailable USB scanner

### ISSUE THREAD

**Issue by meiser79** [SimulPiscator/AirSane#42]
My server running AirSane is a KVM VM. When I power-on my Brother scanner, the device is attached to the VM via a udev rule.
When I power-off the scanner, the device is currently NOT detached from the VM (issue with udev remove rule).

That's why the device is still shown in lsusb output and AirSane thinks that it's still available.

As soon as e.g. AirSane tries to access the scanner because AIC requests a preview scan, AirSane segfaults.

Here's the gdb backtrace (first part is a successful preview scan after powering on the device, the second is the one causing the segfault as device is powered off):
[gdb-backtrace.txt](https://github.com/SimulPiscator/AirSane/files/5709600/gdb-backtrace.txt)

**Comment by SimulPiscator** [comment]
Thank you for the report. In fact, AirSane gets a SANE error when trying to open the switched-off device, and properly ignores it. Access to the scanner object seems to happen from a client thread that was started before the SIGHUP, and the object was deleted during the server reset.

I'll try to fix this issue as soon as I have time.

**Comment by SimulPiscator** [comment]
In the client thread, I was using a reference to a shared_ptr rather than a copy. As a result, scanner objects could be deleted by a device-rescan while still being used in the client thread. The bug is fixed now.

Let me know whether it works better for you now.

**Comment by meiser79** [comment]
The segfault is fixed, thanks!

But AirSane hangs now at sane_open(), I have to restart it so that it works again.
```document format requested: image/jpeg
document format used: image/png
using color gamma of 0.555555
sane_init(nullptr, nullptr)
sane_open(brother4:bus1;dev2) -> hotplug event, reloading configuration
received SIGHUP, reloading
reading device options from '/etc/airsane/options.conf'
enumerating local devices...
sane_get_devices() ...
... sane_get_devices() -> SANE_Status Success
found: brother4:bus1;dev2 (Brother DCP-1510)
sane_open(brother4:bus1;dev2) -> SANE_Status Error during device I/O
error: failed to open device
listening on 192.168.1.2:8090
listening on [ipv6-address]:8090
listening on [fe80::5054:ff:fe21:d971]:8090
SANE_Status Invalid argument
sane_exit()
hotplug event, reloading configuration
received SIGHUP, reloading
reading device options from '/etc/airsane/options.conf'
enumerating local devices...
sane_init(nullptr, nullptr)
sane_get_devices() ...
... sane_get_devices() -> SANE_Status Success
sane_exit()
found: brother4:bus1;dev2 (Brother DCP-1510)
sane_init(nullptr, nullptr)
sane_open(brother4:bus1;dev2) -> 
```

**Comment by SimulPiscator** [comment]
Thanks for the report. I don't think I can do anything about this, as the code hangs in sane_open(). Do you get similar behavior when unplugging/plugging the USB cable rather than powering off the scanner?

**Comment by meiser79** [comment]
Yes, it's exactly the same behaviour when unplugging/plugging the USB cable.

Could you help me understand why you can't do anything if it hangs in sane_open()?

**Comment by SimulPiscator** [comment]
It is the responsibility of the backend to make sure sane_open() terminates, either successfully or with an error. How should I be able to guess when it is safe to call the function, and when not?
