### ISSUE TITLE
Failed to Open a Connection to Device ~ macOS

### ISSUE THREAD

**Issue by asifrasheed6** [SimulPiscator/AirSane#44]
- macOS fails to connect to the scanner (throws an error 21345)
- Scanning works through the web client on macOS
- Cancelled by user error on windows

**Comment by SimulPiscator** [comment]
> macOS fails to connect to the scanner (throws an error 21345)
You need to enable IPv6 in your local network, and on the machine running AirSane. After rebooting the machine running AirSane, you will be able to scan from Apple Image Capture.

**Comment by SimulPiscator** [comment]
> Cancelled by user error on windows

Works for me with Edge, Chrome, and Firefox. By default, the image file is opened with "Microsoft Photos," which may be temporarily unavailable when opened for the first time. Maybe this was the error you experienced?

**Comment by asifrasheed6** [comment]
- The Windows issues isn't with Microsoft Photos, it showed the error message on the webpage itself. However, it disappeared after I restarted the printer and the raspberry pi.
- I will take a look at the IPv6 solution and get back to you.
