### ISSUE TITLE
Unable to locate package libusb-1.*-dev

### ISSUE THREAD

**Issue by elsiehupp** [SimulPiscator/AirSane#46]
When following the `README.md` instructions, I got the following error:
```
$ sudo apt install libusb-1.*-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libusb-1.*-dev
```
I forget how I got it to work when I was initially running through the instructions. This is what I currently have installed:
```
$ apt list --installed | grep libusb

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libusb-0.1-4/focal,now 2:0.1.12-32 amd64 [installed,automatic]
libusb-1.0-0-dev/focal,now 2:1.0.23-2build1 amd64 [installed]
libusb-1.0-0/focal,now 2:1.0.23-2build1 amd64 [installed,automatic]
libusb-1.0-0/focal,now 2:1.0.23-2build1 i386 [installed,automatic]
libusb-1.0-doc/focal,focal,now 2:1.0.23-2build1 all [installed,automatic]
libusb-dev/focal,now 2:0.1.12-32 amd64 [installed]
libusbmuxd6/focal,now 2.0.1-2 amd64 [installed,automatic]
```
Judging by what's installed, it looks like this is what I did that ended up working:
```
$ sudo apt install libusb-1.0-0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libusb-1.0-0-dev is already the newest version (2:1.0.23-2build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
(IIRC I tried installing just `libusb-dev`, since that is indeed also manually installed on my system, but the `make` script didn't like that and insisted I use `libusb-1.0-0-dev` instead.)

So, I guess, if it's okay to specify `libusb-1.0-0-dev` rather than `libusb-1.*-dev`, you could just update that in the instructions.

**Comment by SimulPiscator** [comment]
Thanks for the report!

I replaced the "apt" command with "apt-get" which should continue support for glob expressions in package names (which has been dropped from apt in favor of something different for whatever reason).
