### ISSUE TITLE
Not all resolutions available

### ISSUE THREAD

**Issue by debiantriage** [SimulPiscator/AirSane#5]
A nice, useful application with good instructions for compilation and installation.

I have a local HP aio (a PSC 1300) which offers scan resolutions of 75, 300 and 600 dpi in the browser.
* scanimage -A -d <URI> | grep resolution

returns

* 75|100|150|200|300|600dpi [75].

Is there a reason for the difference?

-- 
Brian.

**Comment by SimulPiscator** [comment]
Right. The web interface only lists the most important resolutions to keep the code simple. If you are using the scanner from a macos client, all resolutions will be available.

-Juergen
