### ISSUE TITLE
Packages for Synology

### ISSUE THREAD

**Issue by itsab1989** [SimulPiscator/AirSane#51]
Hi, this is not really an issue, but can you maybe share some information about how to build / compile (or whatever it's called) Airsane for a Synology Diskstation (DS 414 specifically in my case).
About a year ago I installed a pre-compiled package from pcloadletter as you suggest in your instructions, but the version provided there is quite old by now and I'd like to make use of all of the improvements and new features of Airsane that you added recently.
Please don't get me wrong I'm fully aware that it would be very time consuming for you to compile your app for all those different architectures so I'm really not complaining.
It's just that I have literally no clue how to do it myself. And it's frustrating because SANE means Scanner Access Now Easy. And with your app it is in fact very easy. But still so difficult (for me at least)...

**Comment by SimulPiscator** [comment]
Hi, unfortunately I don't have access to a Synology NAS, so I wouldn't be able to test the packages once built. I'll try to contact the pcloadletter author and ask him to provide an updated package.

**Comment by itsab1989** [comment]
That would be really great. Thanks in advance!

**Comment by patters-syno** [comment]
Looking into it 🙂
