### ISSUE TITLE
[feature request] WSD support

### ISSUE THREAD

**Issue by meiser79** [SimulPiscator/AirSane#52]
Hi,

as I also have some Windows 10 clients, I'd like to also be able to use my network scanner in Windows.

May I ask to integrate WSD support? I know, this is totally different to AirScan, but I hope to see it integrated.

Thanks in advance,
meiser

**Comment by SimulPiscator** [comment]
Hi,

I actually spent quite some effort on adding WSD support but could not get it to work. Windows would detect and recognize the scanner object, request meta data, but never connect to the WSD port proper. I have no idea why. This, together with both considerable lack of documentation, and impenetrability of documentation where it exists, made me give up on the effort.

Sorry,
Simul

**Comment by meiser79** [comment]
Could you maybe publish your efforts in a separate branch? Maybe, some other developers (like the guys from sane-airscan or sane-escl) can give you some hints?

**Comment by SimulPiscator** [comment]
I don't think my efforts are worth to publish. Maybe the author of this repository: https://github.com/roncapat/WSD-python is willing to finish his work on the server side?

**Comment by meiser79** [comment]
continued in #53
