### ISSUE TITLE
Not all page sizes available

### ISSUE THREAD

**Issue by debiantriage** [SimulPiscator/AirSane#6]
Of the three scanners I have tested, one offers A5 and A6 paper size but no A4. The other two do not offer A4 Landscape .

-- 
Brian.

**Comment by SimulPiscator** [comment]
Only those paper sizes will be offered which fit into the scanner's physical scan area. If A4 Portrait is not available for a scanner, this may be because it is US Letter sized rather than A4. When accessing AirSane from a macos client, all paper sizes will be available.

-Juergen

**Comment by SimulPiscator** [comment]
I added US Letter and Legal paper sizes to the web interface, maybe this helps you.
