### ISSUE TITLE
Https ?

### ISSUE THREAD

**Issue by bastien-roucaries** [SimulPiscator/AirSane#65]
Hi,

Does it work over https ? 

It will be better to check if it work over https from a security point of view

**Comment by bastien-roucaries** [comment]
Note that in order to be safer using a proxy like stunnel instead of creating your own certicate and own crypto chain.

KISS please

**Comment by bastien-roucaries** [comment]
In fact we care about your package for securing old scanner.

adding a freedom box will secure old scanner printer

**Comment by SimulPiscator** [comment]
I was thinking about integrating OpenSSL support through a std::streambuf descendant. Would that violate KISS?

**Comment by bastien-roucaries** [comment]
> I was thinking about integrating OpenSSL support through a std::streambuf descendant. Would that violate KISS?
It is usually harder to support all ssl option using the lib and do in a secure way, think about client certificate, perfect forward secret and so on. A lot of option to code.

stunnel over unix socket is KISS simple and audited. This is less security to audit on your side and it is better. KISS

**Comment by bastien-roucaries** [comment]
Note that nginx in transparent proxy accept unix socket KISS

**Comment by SimulPiscator** [comment]
OK, there is a unix socket option now.
