### ISSUE TITLE
Add a no-advice parameter in order to hide version

### ISSUE THREAD

**Issue by bastien-roucaries** [SimulPiscator/AirSane#67]
According to good security pratice using a hardening flag version should be hidded.

https://github.com/SimulPiscator/AirSane/blob/335e832047d718fd119f19b8078904ac93eba08b/server/mainpage.cpp#L62

**Comment by bastien-roucaries** [comment]
(may be they are other part where the version is outputed)

**Comment by SimulPiscator** [comment]
Displaying the version on the server's main page is now optional, but enabled by default. The version is written to stderr at startup if logging is enabled, but that should be ok IMHO.
