### ISSUE TITLE
File naming with more than one Scan.*

### ISSUE THREAD

**Issue by debiantriage** [SimulPiscator/AirSane#7]
I am not a great fan of Scan(2).pdf as a file name because "(" and ")" have to be escaped on the command line. I would alter it to a more convenient Scan-2.pdf if I knew which part of the code to change.

-- 
Brian.

**Comment by SimulPiscator** [comment]
Hi Brian,

file names are managed on the client side. AirSane cannot do anything about this.

-Juergen
