### ISSUE TITLE
Crawling unknown page should raise a log warning

### ISSUE THREAD

**Issue by bastien-roucaries** [SimulPiscator/AirSane#70]
You should get something on stderr if something try to load non existant page. It will defect simple network scanner and raise some warning using log analyser. Use an exception Error404 or so on to do this (see next bug report for why)

At least here
https://github.com/SimulPiscator/AirSane/blob/335e832047d718fd119f19b8078904ac93eba08b/server/mainpage.cpp#L69

**Comment by SimulPiscator** [comment]
I added some code to do this.
