### ISSUE TITLE
404 should be silent if needed

### ISSUE THREAD

**Issue by bastien-roucaries** [SimulPiscator/AirSane#71]
ultra low priority some admin prefer to redirect 404 to something else for security point of view

**Comment by SimulPiscator** [comment]
Right now, a warning is written to stderr when an invalid path is requested, and a 404 Error page is served. Do you suggest to suppress the error page, and not respond anything, just close the connection when 404 would be the response?

**Comment by bastien-roucaries** [comment]
no i means somthing like (please test and add to your server a 404.html page). Thus nginx proxy could log attempt to load 404.html:

header("HTTP/1.1 404 Not Found");
header("Refresh: 0; url=/404.html");
<html>
<head>
<script>
function a(){
  document.location.href="/404.html"; 
}
</script>
</head>
  <body onLoad="setTimeout('a()', 1)">
     <div>Redirect</div>
  </body>
</html>

**Comment by SimulPiscator** [comment]
Why does the page constantly reload itself?

**Comment by bastien-roucaries** [comment]
You are right removed the bad advice

Good advice will be to return 
* header("HTTP/1.1 404 Not Found");
* return a html header file and load the body from /404.xml with a javascript plugin.

But it is superlow priority

**Comment by bastien-roucaries** [comment]
Or better return pure html5 and use import from 404.html https://www.html5rocks.com/en/tutorials/webcomponents/imports/

**Comment by SimulPiscator** [comment]
From the linked site:
> HTML Imports are deprecated and was [removed](https://www.chromestatus.com/feature/5144752345317376) from Chrome in February 2020.
