### ISSUE TITLE
Missing Attribute in ScannerCapabilities XML

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#72]
I believe the attribute of pwg:SerialNumber is required in eSCL protocol. Scanner Capabilities XML generated by this project lacks it, causing me some incompatibilities with eSCL projects that I am working on. You may want to consider adding the attribute . I have tested with several devices and this is the only product I have found that omits this attribute.

**Comment by SimulPiscator** [comment]
The eSCL document says nothing about pwg:SerialNumber but displays it in an example capabilities XML. Anyway, I added a serial number field to capabilities XML.
