### ISSUE TITLE
Suggestion for web server

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#74]
As most people are already running a web server on Linux (CUPS) , consider avoiding the additional web server and integrating this to the CUPS web server if possible. The port is irrelevant.

more info in CUPS  install
http://localhost:631/help/cgi.html
 I can not say that I have cracked it yet for my needs but your needs are different than mine as are your skills.

**Comment by SimulPiscator** [comment]
Thank you for the suggestion. However, as far as I can see, a set of cgi executables cannot do what AirSane does: Auto-detecting and advertising scanners via mDNS.

**Comment by markosjal** [comment]
Well I thought you used Avahi anyway to make those announcements, but maybe I am mistaken. I do see Avahi as a dependency during install. 

Not meaning it is right for you "out of the box" but I do believe there will come a day when we see IPP Printing and IPP Scanning on the same web interface.

**Comment by SimulPiscator** [comment]
Yes, I'm using the avahi API to announce scanners. This requires a client thread that continues running as long as the mDNS announcement lasts. I cannot see how to do this using one or more cgi executables, as those only run during the lifetime of a server request.
