### ISSUE TITLE
Make Install not working

### ISSUE THREAD

**Issue by albertovm** [SimulPiscator/AirSane#80]
Please, I am trying to install AirSane to run with OS X, but I have the following error in my Debian (Raspberry Pi) box. Any idea how to solve this?

> sudo make install
[  4%] Generating version.cpp, _version.cpp
[  8%] Building CXX object CMakeFiles/airsaned.dir/version.cpp.o
/home/pi/AirSane-build/version.cpp:2:26: warning: missing terminating " character
   const char* GIT_BRANCH="Please do not run git as root, your regular user account is enough :)
                          ^
/home/pi/AirSane-build/version.cpp:2:26: error: missing terminating " character
   const char* GIT_BRANCH="Please do not run git as root, your regular user account is enough :)
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/AirSane-build/version.cpp:9:63: warning: missing terminating " character
 You might have to restart your login session after doing that.";
                                                               ^
/home/pi/AirSane-build/version.cpp:9:63: error: missing terminating " character
 You might have to restart your login session after doing that.";
                                                               ^~
/home/pi/AirSane-build/version.cpp:10:31: warning: missing terminating " character
   const char* GIT_COMMIT_HASH="Please do not run git as root, your regular user account is enough :)
                               ^
/home/pi/AirSane-build/version.cpp:10:31: error: missing terminating " character
   const char* GIT_COMMIT_HASH="Please do not run git as root, your regular user account is enough :)
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/AirSane-build/version.cpp:17:63: warning: missing terminating " character
 You might have to restart your login session after doing that.";
                                                               ^
/home/pi/AirSane-build/version.cpp:17:63: error: missing terminating " character
 You might have to restart your login session after doing that.";
                                                               ^~
/home/pi/AirSane-build/version.cpp:18:35: warning: missing terminating " character
   const char* GIT_REVISION_NUMBER="Please do not run git as root, your regular user account is enough :)
                                   ^
/home/pi/AirSane-build/version.cpp:18:35: error: missing terminating " character
   const char* GIT_REVISION_NUMBER="Please do not run git as root, your regular user account is enough :)
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/AirSane-build/version.cpp:33:2: warning: missing terminating " character
 +";
  ^
/home/pi/AirSane-build/version.cpp:33:2: error: missing terminating " character
 +";
  ^~
/home/pi/AirSane-build/version.cpp:4:1: error: ‘If’ was not declared in this scope
 If you need to run git with root rights for some other application than
 ^~
make[2]: *** [CMakeFiles/airsaned.dir/build.make:70: CMakeFiles/airsaned.dir/version.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/airsaned.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

If I do the same without SUDO, I have another error...

> make install
[  8%] Generating version.cpp, _version.cpp
[  8%] Building CXX object CMakeFiles/airsaned.dir/version.cpp.o
[  8%] Linking CXX executable airsaned
[  8%] Built target airsaned
Install the project...
-- Install configuration: "MinSizeRel"
-- Installing: /usr/local/bin/airsaned
CMake Error at cmake_install.cmake:47 (file):
  file INSTALL cannot set modification time on "/usr/local/bin/airsaned":
  Operation not permitted.
make: *** [Makefile:106: install] Error 1

**Comment by SimulPiscator** [comment]
You need to run make as regular user first, then run make install with sudo.
```
make && sudo make install
```
