### ISSUE TITLE
Scanner detected by scanimage but not Airsane

### ISSUE THREAD

**Issue by Kyshman** [SimulPiscator/AirSane#83]
**Server:**
OS: Ubuntu 18.04.6 LTS i686
Kernel: 4.15.0-159-generic

**Scanimage:**
`scanimage -L`
device hp5590:libusb:001:002 is a HP 5590 Workgroup scanner
device hpaio:/par/HP_LaserJet_1100?device=/dev/parport0' is a Hewlett-Packard HP_LaserJet_1100 all-in-one

**Airsane CLI launch**
`sudo /usr/local/bin/airsaned --interface=\* --listen-port=8090 --access-log=- \
                  --hotplug=true --mdns-announce=true --announce-secure=false \
                  --unix-socket= --web-interface=true --random-paths=false \
                  --local-scanners-only=true --disclose-version=true \
                  --reset-option=true --options-file=/etc/airsane/options.conf --ignore-list=/etc/airsane/ignore.conf --debug=true`

**Relevant CLI Output**
> found: hp5590:libusb:001:002 (HP 5590)
stable unique name: hp5590:HP 5590:1
uuid: 975bc2fa-6a5e-5a13-923b-020331495a17
sane_init(nullptr, nullptr)
sane_open(hp5590:libusb:001:002) -> SANE_Status Invalid argument
sane_exit()

The webpage on port 8090 says no scanners available. When airsane is running scanimage output is 

`scanimage -L`
>device `hpaio:/par/HP_LaserJet_1100?device=/dev/parport0' is a Hewlett-Packard HP_LaserJet_1100 all-in-one

Once airsane is stopped the output of scanimage goes back to normal

`scanimage -L`
>device `hp5590:libusb:001:002' is a HP 5590 Workgroup scanner
device `hpaio:/par/HP_LaserJet_1100?device=/dev/parport0' is a Hewlett-Packard HP_LaserJet_1100 all-in-one

I cant figure out why airsane can't open the scanner yet it seems to make it unavailable to scanimage.

**Comment by SimulPiscator** [comment]
I agree that it's strange that sane_open fails with an error code but still keeps some lock on the device so scanimage -L can't find it. I tend to see this as a bug in the hpaio backend.

The other question is whether actual scanning works through scanimage?

**Comment by Kyshman** [comment]
I was actually just going to clarify that for you as you also had me a bit lost whein you mentioned the hpaio backend

>I agree that it's strange that sane_open fails with an error code but still keeps some lock on the device so scanimage -L can't find it. I tend to see this as a bug in the **hpaio backend**.

The LaserJet 1100 is an ancient printer (only) connected on the same box via parallel port while the scanner is the hp5590 on USB which is using the sane-hp5590 backend.

This is the device that keeps disappearing when Airsane is started. We can safely diregard any mention of the 1100.

**Comment by Kyshman** [comment]
>So you can successfully scan from the hp5590 device?

Yes this working fine. I can scan locally on the Ubuntu box. 

Its only when Airsane is started that the device disappears fron the scanimage listing and thus am unable to scan. 

>sane_init(nullptr, nullptr)
sane_open(hp5590:libusb:001:002) -> SANE_Status Invalid argument
sane_exit()

Can further debug info/level be activated?

**Comment by Kyshman** [comment]
I upgraded sane to latest git stable 

`scanimage -V`
>scanimage (sane-backends) 1.0.32.128-3440e; backend version 1.0.32

>One last possibility would be that you have more than one libsane installed at different locations, and airsaned links to a different one than scanimage.

`whereis sane`
>sane: /usr/lib/i386-linux-gnu/sane /usr/lib/sane /etc/sane.d /usr/include/sane /usr/share/sane /usr/share/man/man7/sane.7.gz

So I have only one version of sane installed but the issue still persists

Am now checking on the sane-hp5900 backend to see if I can tweak anything

**Comment by rcambrj** [comment]
I just acquired an old `hp5590` and I'm getting the same problem:

```
sane_init(nullptr, nullptr)
sane_open(hp5590:libusb:001:005) -> SANE_Status Invalid argument
sane_exit()
error: failed to open device
```

I can successfully scan with `scanimage`, but when `airsaned` is running it all breaks.

`scanservjs` on the same machine seems to work. So whatever that's doing, it's working... but I'm concerned about the RPi1 not having enough power to process large documents scanned through the ADF. This is easily solved with a beefier machine, but it's a shame, would have been nice to have it networked with `airsaned`.

**Comment by SimulPiscator** [comment]
One possible difference between `airsaned` and the other programs is that the other programs call `sane_open()` from the main thread whereas `airsaned` does so from a secondary thread. To test this, I created a branch "testing" that you might try.

**Comment by rcambrj** [comment]
Thanks for trying, I ran `cmake` and `sudo make install` on that branch, but the failure is the same 😞

**Comment by SimulPiscator** [comment]
Did you do a `sudo systemctl restart airsaned` after `make install`?
