### ISSUE TITLE
Not work after Reboot

### ISSUE THREAD

**Issue by chodorenko** [SimulPiscator/AirSane#84]
Hello,
After reboot computer AirSaned start which systemd and work not correct. Not show Icons and not find scanner by network. Please view screen [Screen_1](https://drive.google.com/file/d/1ar8xL42bcKE4yDKzazmarr0NjQs9Lxu-/view?usp=sharing)
After reboot service, or connect disconnect scanner, or press Reset link on local site service reload and work correct 
[Screen_2](https://drive.google.com/file/d/1I9WyL1FUYS4GvwfKfbcLhlza8To0sNDv/view?usp=sharing)

I reboot computer which --debug=true flag and view connect not all network interfaces on first start, May be need add requirements on Systemd init or check new interfaces UP ?

chodorenko:/home/chodorenko # journalctl -u airsaned
-- Logs begin at Wed 2022-02-02 21:40:09 +03, end at Thu 2022-02-03 00:40:08 +03. --
Feb 02 21:40:10 chodorenko systemd[1]: Started AirSane Imaging Service.
Feb 02 21:40:10 chodorenko airsaned[1207]: git commit: N/A (branch N/A, rev N/A+)
Feb 02 21:40:10 chodorenko airsaned[1207]: build date: 2022-02-02T12:00:00Z
Feb 02 21:40:10 chodorenko airsaned[1207]: reading device options from '/etc/airsane/options.conf'
Feb 02 21:40:10 chodorenko airsaned[1207]: enumerating local devices...
Feb 02 21:40:10 chodorenko airsaned[1207]: sane_init(nullptr, nullptr)
Feb 02 21:40:10 chodorenko airsaned[1207]: sane_get_devices() ...
Feb 02 21:40:10 chodorenko airsaned[1207]: ... sane_get_devices() -> SANE_Status Success
Feb 02 21:40:10 chodorenko airsaned[1207]: sane_exit()
Feb 02 21:40:10 chodorenko airsaned[1207]: found: pixma:04A927D1_0173KG41024E (CANON Canon i-SENSYS MF230 Series)
Feb 02 21:40:10 chodorenko airsaned[1207]: stable unique name: pixma:CANON Canon i-SENSYS MF230 Series:1
Feb 02 21:40:10 chodorenko airsaned[1207]: uuid: cd53ef86-371e-5ecd-9ec7-a0ffc33438cf
Feb 02 21:40:10 chodorenko airsaned[1207]: sane_init(nullptr, nullptr)
Feb 02 21:40:11 chodorenko airsaned[1207]: sane_open(pixma:04A927D1_0173KG41024E) -> 0x7ff7c401e2b0
Feb 02 21:40:11 chodorenko airsaned[1207]: [source] := "Flatbed" -> reload options
Feb 02 21:40:11 chodorenko airsaned[1207]: [source] := "Automatic Document Feeder" -> reload options
Feb 02 21:40:11 chodorenko airsaned[1207]: sane_close(0x7ff7c401e2b0)
Feb 02 21:40:11 chodorenko airsaned[1207]: sane_exit()
Feb 02 21:40:11 chodorenko airsaned[1207]: published as 'CANON Canon i-SENSYS MF230 Series'
Feb 02 21:40:11 chodorenko airsaned[1207]: listening on 127.0.0.1:8090
Feb 02 21:40:11 chodorenko airsaned[1207]: listening on [::1]:8090
Feb 02 21:40:25 chodorenko airsaned[1207]: Warning: Error 404 when requesting "/favicon.ico"
Feb 02 21:41:43 chodorenko airsaned[1207]: Warning: Error 404 when requesting ""
Feb 02 21:41:52 chodorenko airsaned[1207]: received SIGHUP, reloading
Feb 02 21:41:52 chodorenko airsaned[1207]: reading device options from '/etc/airsane/options.conf'
Feb 02 21:41:52 chodorenko airsaned[1207]: enumerating local devices...
Feb 02 21:41:52 chodorenko airsaned[1207]: sane_init(nullptr, nullptr)
Feb 02 21:41:52 chodorenko airsaned[1207]: sane_get_devices() ...
Feb 02 21:41:53 chodorenko airsaned[1207]: ... sane_get_devices() -> SANE_Status Success
Feb 02 21:41:53 chodorenko airsaned[1207]: sane_exit()
Feb 02 21:41:53 chodorenko airsaned[1207]: found: pixma:04A927D1_0173KG41024E (CANON Canon i-SENSYS MF230 Series)
Feb 02 21:41:53 chodorenko airsaned[1207]: stable unique name: pixma:CANON Canon i-SENSYS MF230 Series:1
Feb 02 21:41:53 chodorenko airsaned[1207]: uuid: cd53ef86-371e-5ecd-9ec7-a0ffc33438cf
Feb 02 21:41:53 chodorenko airsaned[1207]: sane_init(nullptr, nullptr)
Feb 02 21:41:54 chodorenko airsaned[1207]: sane_open(pixma:04A927D1_0173KG41024E) -> 0x7ff7c402a0d0
Feb 02 21:41:54 chodorenko airsaned[1207]: [source] := "Flatbed" -> reload options
Feb 02 21:41:54 chodorenko airsaned[1207]: [source] := "Automatic Document Feeder" -> reload options
Feb 02 21:41:54 chodorenko airsaned[1207]: sane_close(0x7ff7c402a0d0)
Feb 02 21:41:54 chodorenko airsaned[1207]: sane_exit()
Feb 02 21:41:54 chodorenko airsaned[1207]: published as 'CANON Canon i-SENSYS MF230 Series'
Feb 02 21:41:54 chodorenko airsaned[1207]: listening on 127.0.0.1:8090
Feb 02 21:41:54 chodorenko airsaned[1207]: listening on 192.168.1.11:8090
Feb 02 21:41:54 chodorenko airsaned[1207]: listening on [::1]:8090
Feb 02 21:41:54 chodorenko airsaned[1207]: listening on [fe80::da3b:bfff:fe22:317f]:8090

**Comment by SimulPiscator** [comment]
Hi,
the log shows that airsane is listening on all interfaces. If you point your browser to 192.168.1.11:8090, do you get the airsane page?

**Comment by chodorenko** [comment]
No its no true , first start on 
Feb 02 21:40:11 chodorenko airsaned[1207]: listening on 127.0.0.1:8090
Feb 02 21:40:11 chodorenko airsaned[1207]: listening on [::1]:8090

After reload bind to all interfaces
Feb 02 21:41:54 chodorenko airsaned[1207]: listening on 127.0.0.1:8090
Feb 02 21:41:54 chodorenko airsaned[1207]: listening on 192.168.1.11:8090
Feb 02 21:41:54 chodorenko airsaned[1207]: listening on [::1]:8090
Feb 02 21:41:54 chodorenko airsaned[1207]: listening on [fe80::da3b:bfff:fe22:317f]:8090




And i try start which option  INTERFACE=lo and i get at the same problems on web interface as illustrated on   Screen_1

**Comment by SimulPiscator** [comment]
The airsane systemd configuration file tries to wait for all interfaces to be up, so I don't understand why you cannot connect to 192.168.1.11:8090.

Still, you might try to add
`ExecStartPre=/bin/sleep 15`
into the systemd service file. This has helped other users with similar problems.

**Comment by chodorenko** [comment]
yes its true , its fix problem, May be good idea add its to default systemd unit in you git.
