### ISSUE TITLE
Just a question about this

### ISSUE THREAD

**Issue by markosjal** [SimulPiscator/AirSane#9]
I am not a programmer at all but find myself deepely involved in supporting a specific scanner that has pretty bad driver support.  I have created a web interface that allows it to scan from anywhere on the network by way of a Linux host. I would like to add Apple AirScan compatibility to it if possible, so that the host listens for airscan requests and passes them along to the scanner, even if some features like PDF require the use of imagemagick

It seems you had to disassemble the AirScan protocol and emulate it .

I would like to know if you could be so kind ... are these two parts the most responsible for listening for AirScan Requests? It seems these are the most relevant.

airsaned.default	Listening by interface rather than address to fix IPv6 issue	a year ago
airsaned.service	Listening by interface rather than address to fix IPv6 issue	a year ago

I am looking for a way to get airscan service added to my custom webserver so that iOS devices will work with it.I thought you might offer a pointer or two?

**Comment by SimulPiscator** [comment]
Hi,

first make sure to read the basic description of the AirScan protocol here:
http://testcluster.blogspot.com/2014/03/scanning-from-escl-device-using-command.html
Then, you will need to implement the following elements of the AirScan protocol:
1) announce the scanner through mdns (zeroconf) with its web location,
2) provide a scanner capabilities xml document for download from that web location,
3) process a scan request xml when sent to the scanner's web location, and redirect to the new scan job's web location,
4) provide a scan job status xml for download from the scan job's web location,
5) provide a scanner status xml for download from the scanner's web location.
In AirSane, the respective code locations are
1) https://github.com/SimulPiscator/AirSane/blob/606f3a048a980459b6e4d71c2a71c9a605a4a62e/server/scanserver.cpp#L139
2) https://github.com/SimulPiscator/AirSane/blob/606f3a048a980459b6e4d71c2a71c9a605a4a62e/server/scanner.cpp#L146
3) https://github.com/SimulPiscator/AirSane/blob/606f3a048a980459b6e4d71c2a71c9a605a4a62e/server/scanjob.cpp#L155
4) https://github.com/SimulPiscator/AirSane/blob/606f3a048a980459b6e4d71c2a71c9a605a4a62e/server/scanjob.cpp#L292
5) https://github.com/SimulPiscator/AirSane/blob/606f3a048a980459b6e4d71c2a71c9a605a4a62e/server/scanner.cpp#L578
To me, it seems that it might be easier for you to write a SANE backend for your device, and then use AirSane to export it, than to write your own AirScan daemon.

**Comment by markosjal** [comment]
I question as to why SANE has never implemented a "File" interface like
USB, Parallel, etc. In that way many command line scanners can be used as
there seems to be a growing list of them.

You would only need to define scanner capabilities , and the command line
options so that SANE can use them and pass them along as necessary

**Comment by markosjal** [comment]
I have written a web front end that runs on Apache and PHP (this is what I know how to do , not a SANE , Flinstones compatible in the age of the Jetsons) , after all this is really what we are dealing with here anyway is web type traffic. 

I am trying to understand this but mabe you could tell me in English 
at #4 and # 5 above
provide a scan job status xml for download from the scan job's web location,
provide a scanner status xml for download from the scanner's web location.
In AirSane, the respective code locations are

I have the 201 Created header being sent with Location /eSCL/Scans. Vuescan (eSCL mode) and Mopria Get this and move to the next step 

This works fine on VueScan (eSCL) , however the Mopria client on Android does a GET /eSCL/ScannerStatus.  After three GETs or so of eSCL/ScannerStatus, it then says "Scan Failed" on Mopria

As far as I have found there are only three conditions that I have seen in ScannerStatus "Idle" , "Processing" and "Stopped". What "Status" is it looking for? Something like "JobReady". I am currently setting ScannerStatus to "Idle" after "Processing" but it seems this is the step I have wrong.

I do not have the luxury of an eSCL Scanner here now so I can not use wireshark to debug a real eSCL scanner, and it will be some months before I can.

Trying to install this package with sane-test getting many many errors which opening new ticket for.
