### ISSUE TITLE
Broken absolute URLs in web interface for .local domain

### ISSUE THREAD

**Issue by dsiguero** [SimulPiscator/AirSane#90]
After setting AirSane up and checking that I was able to acquire images from my OS, I gave the web UI a try. However, both the link to the scanner (and its icon) are broken as it's not taking into account the `.local` domain for the hostname. But both of them work if I try to access them manually (adding `.local`).

Current link: `http://<hostname>:8090/eSCL/`
Expected (working) link: `http://<hostname>.local:8090/eSCL/` 

The Reset link under Server Maintenance is working, as it uses a relative URL, instead of an absolute one.

Could all the URLs be made relative, to solve this issue?

**Comment by SimulPiscator** [comment]
Thanks for the suggestion, I've made all those links relative.

**Comment by dsiguero** [comment]
Thank you for the speedy reply and fix! Closing this as it's fixed now. Also kudos for such great project!
