### ISSUE TITLE
Error with Mustek Bearpaw 1200 CU with scanimage: sane_start: Invalid argument

### ISSUE THREAD

**Issue by matkor** [SimulPiscator/AirSane#94]
I am running airsaned   commit: 806e57d (branch master, revision 247) on Ubuntu 20.04.5 LTS.

Though scanning previews works via http://192.168.3.41:8090/eSCL ,
scanner seems be available:
```
$ scanimage -L
device `escl:http://192.168.3.41:8090' is a ESCL Mustek Bearpaw 1200 CU Plus flatbed scanner
```

Any try to scan fails with:
```
$ scanimage -d 'escl:http://192.168.3.41:8090' > t.img
Output format is not set, using pnm as a default.
Capability : [(null)]
Capability : [image/jpeg]
Capability : [image/png]
scanimage: rounded value of br-x from 0 to 0
scanimage: rounded value of br-y from 0 to 0
scanimage: sane_start: Invalid argument

```

**Comment by SimulPiscator** [comment]
Unfortunately, the escl SANE backend is not compatible with AirSane. You will need to use the [sane-airscan backend](https://github.com/alexpevzner/sane-airscan). It should be available in your distribution through `sudo apt install sane-airscan`.

**Comment by matkor** [comment]
Absolutely right. 
Using -d "airscan:e0:Mustek Bearpaw 1200 CU Plus" seems to work very well.
Thanks for explanation!
